### ISSUE TITLE
xscale moduel not importing at all

### ISSUE THREAD

**Issue by mada0007** [serazing/xscale#17]
Hello I am still a beginner to python in general and xscale in particular. I opened my anaconda environment from mac terminal and installed xscale using the following commands
git clone https://github.com/serazing/xscale.git
cd xscale
python setup.py install
it works well but when I run the test command 
cd xscale
py.test xscale
i get this error
platform darwin -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /Users/mada0007/xscale/xscale/xscale/xscale/xscale, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.1
collecting ... 
========================= no tests ran in 0.00 seconds =========================
ERROR: file not found: xscale

when I try to open xcale from pycharm also I get this error
Traceback (most recent call last):
  File "/Users/mada0007/anaconda3/envs/RAWORK/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-12821310c045>", line 1, in <module>
    from xscale import fitting as ft
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'xscale'

Any help towards achieving this will be very beneficial to me and thanks in advance.

**Comment by mada0007** [comment]
Thanks very much, it works on Jupyter notebook. Advice well taken also.
