### ISSUE TITLE
Error window convolve

### ISSUE THREAD

**Issue by apatlpo** [serazing/xscale#9]
Hi,

The following code crashes and we are wondering whether you guys have an idea of what's going on:

```
# Python 2/3 compatibility
from __future__ import absolute_import, division, print_function
# Pytest
# import pytest
# from xscale.filtering import linearfilters
# from xscale.signal.generator import example_xyt
# Pandas
import pandas as pd
# Xarray
import xarray as xr
# Xscale
import xscale
# Dask
import dask.array as da
# Numpy
import numpy as np
# Scipy
import scipy.signal as sig
# Matplotlib
import matplotlib.pyplot as plt

def example_x(boundaries=False):
	"""
	Generate a  one spatial dimensions ['x'] on a
	regular grid.
	"""
	nx = 128
	x = np.linspace(0, 2 * np.pi, nx)
	# t, y, x = np.meshgrid(t1d, y1d, x1d, indexing='ij')

	# Create a spatio-temporal gaussian noise
	noise = 0.8 * np.random.normal(0, 0.2, nx)

	# Create four spatial patterns
	z1 = np.sin(x) 
	z2 = np.sin(2.5 * x)
	z3 = np.sin(x)
	z4 = np.sin(2.5 * x)
	z = z1 + z2 + z3 + z4 + noise
	if boundaries:
		z[0:nx/4] = np.nan
	output = xr.DataArray(z, coords=[x], dims=['x'],name='z')
	return output.chunk({'x': 70})



foo = example_x()
plt.plot(foo)
w = foo.window
w.set()
# w.set(window={'x':'hann'})
w.plot()
plt.show()
res = w.convolve(compute=False)

plt.show()
```

```
/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/xarray/core/formatting.py:16: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import OutOfBoundsDatetime
/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/xscale-0.1.dev0+15.g78abfdd-py2.7.egg/xscale/filtering/linearfilters.py:241: RuntimeWarning: divide by zero encountered in log10
  response = 20 * np.log10(np.abs(spectrum / abs(spectrum).max()))
f3db=0.059217
f6db=0.098695
Traceback (most recent call last):
  File "xscale_test.py", line 54, in <module>
    res = w.convolve(compute=False)
  File "/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/xscale-0.1.dev0+15.g78abfdd-py2.7.egg/xscale/filtering/linearfilters.py", line 159, in convolve
    coeffs = self.coefficients / np.sum(self.coefficients)
  File "/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1812, in sum
    return sum(axis=axis, dtype=dtype, out=out, **kwargs)
TypeError: sum() got an unexpected keyword argument 'out'
```

**Comment by apatlpo** [comment]
Hi,
We did the following change in xscale/filtering/linearfilters.py

```
		# Check if the data has more dimensions than the window and add
		# extra-dimensions to the window if it is the case
		# coeffs = self.coefficients / np.sum(self.coefficients)
		coeffs = self.coefficients / self.coefficients.sum()
```

It's seems to fix the bug. Do you think it's correct?

**Comment by serazing** [comment]
Indeed, it should work and is compatible with dask array as well. I have made this modification on the fft branch. I will try to merge this branch soon with master.

By the way, if you want to use the window object for convolution you should precise the size of the window with the keyword `n`. The default window length is set to the size of the data dimensions. Use `print(w)` to see the window characteristics. These default values are useful to tapper the data with a window of the same size. In practice, you should not have very large window for convolution.

**Comment by apatlpo** [comment]
We found another issue with the following example:
```
import xscale.signal.generator as xgen

foo = xgen.example_xyt()
w = foo.window
w.set(n={'x': 11, 'y': 21}, window={'x':'hanning', 'y':('tukey', 0.25)})
w.convolve(compute=False).visualize() 
```

which leads to:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-09f9f778a157> in <module>()
     11 w = foo.window
     12 w.set(n={'x': 11, 'y': 21}, window={'x':'hanning', 'y':('tukey', 0.25)})
---> 13 w.convolve(compute=False).visualize()

/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/xscale-0.1.dev0+15.g78abfdd-py2.7.egg/xscale/filtering/linearfilters.py in convolve(self, mode, weights, compute)
    162                 mask = self.obj.notnull()
    163                 if weights is None:
--> 164                         weights = im.convolve(mask.astype(float), coeffs, mode=mode)
    165                 filled_data = self.obj.fillna(0.).data
    166

/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in convolve(input, weights, output, mode, cval, origin)
    815     """
    816     return _correlate_or_convolve(input, weights, output, mode, cval,
--> 817                                   origin, True)
    818
    819

/home1/homedir5/perso/slgentil/.miniconda2/envs/xscale/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in _correlate_or_convolve(input, weights, output, mode, cval, origin, convolution)
    647     wshape = [ii for ii in weights.shape if ii > 0]
    648     if len(wshape) != input.ndim:
--> 649         raise RuntimeError('filter weights array has incorrect shape.')
    650     if convolution:
    651         weights = weights[tuple([slice(None, None, -1)] * weights.ndim)]

RuntimeError: filter weights array has incorrect shape.
```

self.coefficients is indeed 2D while mask is 3D.
Any idea what's going wrong?

cheers

aurelien

**Comment by apatlpo** [comment]
The issue was apparently due to the install and the test script.
The following is working:
```
# install
bash
conda create --name xscale python
source activate xscale
conda config --add channels conda-forge
conda install numpy
conda install scipy
conda install xarray
conda install numba

git clone https://github.com/serazing/xscale.git
cd xscale
git pull origin fft
python setup.py install

cd ..
python test.py
```

with test.py:
```
import xscale.signal.generator as xgen
import matplotlib.pyplot as plt
foo = xgen.example_xyt()
print foo
w = foo.window
w.set(n={'x': 11, 'y': 21}, window={'x':'hanning', 'y':('tukey', 0.25)})
w.convolve(compute=False).isel(time=0).plot()
plt.show()
```

**Comment by serazing** [comment]
Should I close the issue ?

**Comment by apatlpo** [comment]
yes

**Comment by apatlpo** [comment]
done
